export const all = '[data-testkey="all"]'
export const goals = '[data-testkey="goals"]'
export const playerGoals = '[data-testkey="player goals"]'
export const fistHalf = '[data-testkey="1. half"]'
export const secondHalf = '[data-testkey="2. Half"]'
